version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
<<<<<<< before updating
      interval: "monthly"
=======
      interval: 'monthly'
    groups:
      github-actions:
        patterns:
          - '*'
>>>>>>> after updating
    labels:
      - "part: github_actions"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 7
    groups:
      javascript:
        patterns:
          - '*'
    labels:
      - "lang: javascript"
      - "part: dependencies"
